import turtle
turtle.speed(100)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor('dark blue')

#синее основание
turtle.forward(200)
turtle.left(70)
turtle.forward(150)
turtle.left(110)
turtle.forward(303)
turtle.right(70)
turtle.forward(50)
turtle.left(70)
turtle.forward(50)
turtle.left(180)
turtle.penup()
turtle.forward(50)
turtle.right(70)
turtle.forward(50)
turtle.pendown()
turtle.forward(125)
turtle.penup()
turtle.forward(25)
turtle.pendown()
turtle.forward(30)
turtle.left(70)
turtle.forward(180)

#колеса
turtle.penup()
turtle.right(160)
turtle.forward(30)
turtle.pendown()
turtle.dot(30)
turtle.right(20)
turtle.penup()
turtle.forward(120)
turtle.pendown()
turtle.dot(30)

#решетка
turtle.right(75)
turtle.penup()
turtle.forward(45)
turtle.right(110)
turtle.forward(15)
turtle.left(110)
turtle.pendown()
turtle.pencolor('light blue')
turtle.forward(137)
turtle.right(105)
turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.pendown()
turtle.forward(130)
turtle.left(90)
turtle.penup()
turtle.forward(50)
turtle.left(75)
turtle.pendown()
turtle.forward(137)
turtle.right(75)
turtle.penup()
turtle.forward(50)
turtle.right(110)
turtle.forward(50)
turtle.right(70)
turtle.pendown()
turtle.forward(257)
turtle.left(110)
turtle.penup()
turtle.forward(50)
turtle.left(70)
turtle.pendown()
turtle.forward(230)

turtle.done()

turtle.down()