import turtle
turtle.speed(10000000)
turtle.pendown()
turtle.pensize(2)
turtle.pencolor('white')

turtle.begin_fill()
turtle.fillcolor('light blue')
turtle.right(10)
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 100)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor('blue')
turtle.right(180)
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 30)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor('green')
turtle.right(180)
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 55)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor('yellow')
turtle.right(180)
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 85)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.begin_fill()
turtle.fillcolor('red')
turtle.right(180)
turtle.forward(150)
turtle.left(90)
turtle.circle(150, 90)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()

turtle.done()
turtle.down()